/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardDeck {
    }
    interface FrameButton {
    }
    interface FrameCard {
    }
    interface FrameCardBody {
    }
    interface FrameCardFooter {
    }
    interface FrameCardHeader {
    }
    interface FrameCardImage {
        "alt": string;
        "image": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCardDeckElement extends Components.CardDeck, HTMLStencilElement {
    }
    var HTMLCardDeckElement: {
        prototype: HTMLCardDeckElement;
        new (): HTMLCardDeckElement;
    };
    interface HTMLFrameButtonElement extends Components.FrameButton, HTMLStencilElement {
    }
    var HTMLFrameButtonElement: {
        prototype: HTMLFrameButtonElement;
        new (): HTMLFrameButtonElement;
    };
    interface HTMLFrameCardElement extends Components.FrameCard, HTMLStencilElement {
    }
    var HTMLFrameCardElement: {
        prototype: HTMLFrameCardElement;
        new (): HTMLFrameCardElement;
    };
    interface HTMLFrameCardBodyElement extends Components.FrameCardBody, HTMLStencilElement {
    }
    var HTMLFrameCardBodyElement: {
        prototype: HTMLFrameCardBodyElement;
        new (): HTMLFrameCardBodyElement;
    };
    interface HTMLFrameCardFooterElement extends Components.FrameCardFooter, HTMLStencilElement {
    }
    var HTMLFrameCardFooterElement: {
        prototype: HTMLFrameCardFooterElement;
        new (): HTMLFrameCardFooterElement;
    };
    interface HTMLFrameCardHeaderElement extends Components.FrameCardHeader, HTMLStencilElement {
    }
    var HTMLFrameCardHeaderElement: {
        prototype: HTMLFrameCardHeaderElement;
        new (): HTMLFrameCardHeaderElement;
    };
    interface HTMLFrameCardImageElement extends Components.FrameCardImage, HTMLStencilElement {
    }
    var HTMLFrameCardImageElement: {
        prototype: HTMLFrameCardImageElement;
        new (): HTMLFrameCardImageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "card-deck": HTMLCardDeckElement;
        "frame-button": HTMLFrameButtonElement;
        "frame-card": HTMLFrameCardElement;
        "frame-card-body": HTMLFrameCardBodyElement;
        "frame-card-footer": HTMLFrameCardFooterElement;
        "frame-card-header": HTMLFrameCardHeaderElement;
        "frame-card-image": HTMLFrameCardImageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CardDeck {
    }
    interface FrameButton {
    }
    interface FrameCard {
    }
    interface FrameCardBody {
    }
    interface FrameCardFooter {
    }
    interface FrameCardHeader {
    }
    interface FrameCardImage {
        "alt"?: string;
        "image"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "card-deck": CardDeck;
        "frame-button": FrameButton;
        "frame-card": FrameCard;
        "frame-card-body": FrameCardBody;
        "frame-card-footer": FrameCardFooter;
        "frame-card-header": FrameCardHeader;
        "frame-card-image": FrameCardImage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-deck": LocalJSX.CardDeck & JSXBase.HTMLAttributes<HTMLCardDeckElement>;
            "frame-button": LocalJSX.FrameButton & JSXBase.HTMLAttributes<HTMLFrameButtonElement>;
            "frame-card": LocalJSX.FrameCard & JSXBase.HTMLAttributes<HTMLFrameCardElement>;
            "frame-card-body": LocalJSX.FrameCardBody & JSXBase.HTMLAttributes<HTMLFrameCardBodyElement>;
            "frame-card-footer": LocalJSX.FrameCardFooter & JSXBase.HTMLAttributes<HTMLFrameCardFooterElement>;
            "frame-card-header": LocalJSX.FrameCardHeader & JSXBase.HTMLAttributes<HTMLFrameCardHeaderElement>;
            "frame-card-image": LocalJSX.FrameCardImage & JSXBase.HTMLAttributes<HTMLFrameCardImageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
